config/routes.rb
Rails.application.routes.draw do
  root       'static_pages#home'

  get       'projects' => 'projects#index'
  get       'report'  => 'projects#show'
  get       'about'    => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_base_path(api_key)
    RestClient::Resource.new('https://app.asana.com/api/1.0/',
                                    user: api_key, password: '')
  end

  def convert_to_json(hash)
    JSON.parse(hash)['data']
  end

  def get_projects(base_path, workspaces)
    begin
      projects = base_path['projects?opt_fields=name,workspace.name,team.name&archived=false'].get
    rescue => e
      case
      when e.message.include?("401")
        flash[:danger] = "Sorry, Asana doesn't recognize that API key."
      else
        flash[:danger] = "Sorry, we seem to be having trouble contacting Asana.\nTry again later!"
      end
      return false
    end
    projects = convert_to_json(projects)
    projects.sort_by {|p| p['workspace']['name']}
  end

  def get_tasks(base_path, project, start_date, end_date)
    begin
      tasks = base_path["projects/#{project}/tasks?opt_fields=tags.name,assignee.name,completed_at"].get
    rescue => e
      flash.now[:danger] = "Sorry, something went wrong. Please try again."
    end
    tasks.empty? ? false : tasks = convert_to_json(tasks)
    tasks.empty? ? false : tasks = trim_end_date(tasks, start_date, end_date)
    tasks.empty? ? false : tasks = remove_extra_tags(tasks)
    tasks.empty? ? false : tasks = fix_unassigned(tasks)
  end

  def trim_end_date(tasks, start_date, end_date)
    tasks.select! { |task| task['completed_at'] != nil }
    tasks.select { |task| Date.parse(task['completed_at']) <= end_date && Date.parse(task['completed_at']) >= start_date }
  end

  def remove_extra_tags(tasks)
    tasks.each do |task|
      task['tags'].select! { |key, value| key['name'].to_i > 0 }
    end
    tasks.select! { |task| !task['tags'].empty? }
  end

  def fix_unassigned(tasks)
    tasks.each do |task|
      if task['assignee'].nil?
        task['assignee'] = {}
        task['assignee']['name'] = "Unassigned"
      end
    end
  end

  def generate_report(tasks)
    gather_points(tasks)
  end

  def gather_points(tasks)
    points = {}
    tasks.each do |task|
      if points[task['assignee']['name']].nil?
        points[task['assignee']['name']] = []
      end
      points[task['assignee']['name']] << task['tags'].first['name'].to_i
    end
    points
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   def index
    if session[:api_key].empty?
      api_key           = user_params[:api_key]
      session[:api_key] = user_params[:api_key]
    else
      api_key = session[:api_key]
    end

    base_path  = set_base_path(api_key)
    @projects   = get_projects(base_path, @workspaces)

    if @projects == false
      redirect_to root_path
    end
  end

  def show
    api_key       = session[:api_key]
    base_path     = set_base_path(api_key)
    @project_id   = project_params[:id]
    @project_name = project_params[:name]

    if project_params[:start_date].nil?
      @start_date = Date.today - Date.today.wday
      @end_date   = @start_date + 6
    else
      @start_date = Date.parse(project_params[:start_date])
      @end_date   = Date.parse(project_params[:end_date])
    end

    @tasks = get_tasks(base_path, @project_id, @start_date, @end_date)

    if @tasks
      @report = generate_report(@tasks)
    else
      @report = false
    end
  end

  private
    def project_params
      params.require(:project).permit(:id, :name, :start_date, :end_date)
    end

    def user_params
      params.require(:user).permit(:api_key)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if session[:api_key]
      if !session[:api_key].empty?
        session[:api_key] = []
        flash.now[:info] = "API Key cleared from session"
      end
    else
      session[:api_key] = []
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
    base_title = "Asana Iguana"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def header_left_link
    if session[:api_key].empty?
      link_to 'Asana Iguana!', root_path
    else
      link_to 'Clear API Key', root_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def set_week(week_type: false, date_type: false, start_date: false)
    case week_type
    when :prev
      case date_type
      when :start
        start_date - start_date.wday - 7
      when :end
        start_date - start_date.wday - 1
      end
    when :this
      case date_type
      when :start
        Date.today - Date.today.wday
      when :end
        Date.today - Date.today.wday + 6
      end
    when :next
      case date_type
      when :start
        start_date - start_date.wday + 7
      when :end
        start_date - start_date.wday + 13
      end
    else
      false
    end
  end

  def button_text(type)
    case type
    when :prev
      "< Week"
    when :this
      "Current Week"
    when :next
      "Week >"
    else
      false
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/layouts/_header.html.erb
<%= navbar do %>
  <%= vertical do %>
    <%= header_left_link %>
  <% end %>
  <%= horizontal do %>
    <%= nav class: 'navbar-right' do %>
      <%= link_to 'Github Source', 'https://github.com/Tohsig/asana-iguana' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" />
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row" >
      <div class="col-xs-12 text-center">
        <% flash.each do |msg_type, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_date_picker.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <h1><%= @project_name %></h1>
    <%= link_to 'Back to Projects List', projects_path %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <div class="" id="custom-date">
      <%= form_tag({controller: "projects", action: "show"}, method: "get", class: "form-inline input") do %>
        <%= hidden_field_tag "project[id]", @project_id %>
        <%= hidden_field_tag "project[name]", @project_name %>
        <%= date_field_tag "project[start_date]",
                           @start_date, class: "form-control date" %>
        <div class="form-group">
          <%= label_tag "project[end_date]", "to", id: "date-spacer" %>
          <%= date_field_tag "project[end_date]",
                             @end_date, class: "form-control date" %>
        </div>
        <%= submit_tag "Go!", class: "btn btn-primary", id: "date-btn" %>
      <% end %>
    </div>
    <h3><%= @start_date.to_s(:long) %> to <%= @end_date.to_s(:long) %></h3>
  </div>
</div>

<div class="row text-center">
  <div class="col-sm-offset-3 col-sm-2">
    <%= render partial: "week_button", locals: {type: :prev} %>
  </div>
  <div class="col-sm-2">
    <%= render partial: "week_button", locals: {type: :this} %>
  </div>
  <div class="col-sm-2">
    <%= render partial: "week_button", locals: {type: :next} %>
  </div>
</div>

app/views/projects/_points_list.html.erb
<div class="row points-list">
  <div class="col-md-6 col-md-offset-3 text-center">
      <% if @report %>
        <% @report.each do |key, value| %>
          <div class="row user-row">
              <div class="col-sm-6 user-name">
                <%= key %>
              </div>
              <div class="col-sm-6 user-points">
                <%= value.sum %> points
              </div>
          </div>
        <% end %>
      <% else %>
        <%= alert_box 'No tasks with points for this date range.' %>
      <% end %>
  </div>
</div>

app/views/projects/_projects_list.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <% if !@projects.empty? %>
      <% current_workspace = "" %>
      <% current_team      = "" %>
      <% @projects.each do |project| %>
        <% new_workspace = project['workspace']['name'] %>
        <% new_team      = project['team']['name'] %>
        <% if new_workspace != current_workspace %>
          <h2><%= "#{new_workspace}" %></h2>
          <% current_workspace = new_workspace %>
        <% end %>
        <div class="row project-row">
          <%= link_to report_path(project: { id: project['id'], name: project['name']}) do %>
            <div class="col-sm-6 project-name">
              <%= "#{project['name']}"%>
            </div>
            <div class="col-sm-6 project-team">
              <%= "#{project['team']['name']}"%>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/_week_button.html.erb
<%= form_tag({controller: "projects", action: "show"}, method: "get") do %>
  <%= hidden_field_tag "project[id]", @project_id %>
  <%= hidden_field_tag "project[name]", @project_name %>
  <%= hidden_field_tag "project[start_date]",
                       set_week(start_date: @start_date, week_type: type, date_type: :start) %>
  <%= hidden_field_tag "project[end_date]",
                       set_week(start_date: @start_date, week_type: type, date_type: :end) %>
  <%= submit_tag "#{button_text(type)}", class: "btn btn-primary" %>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, "Projects List") %>
<%= render partial: 'projects_list' %>

app/views/projects/show.html.erb
<% provide(:title, "Report") %>
<%= render partial: 'date_picker' %>
<%= render partial: 'points_list' %>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <h2>Enter your Asana API Key:</h2>
    <%= form_tag({controller: "projects", action: "index"}, method: "get", class: "form_control") do %>
      <%= text_field_tag "user[api_key]", '', autocomplete: "off", id: "home-input" %>
      <p>
        <%= submit_tag "List Projects", class: "btn btn-primary btn-lg" %>
      </p>
    <% end %>
  </div>
</div>
<div class="row text-center" id="overview-box">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-4">
        <h3>What is this?</h3>
        <p>It's a tool to quickly tally up Agile story points based solely off
        of Asana tags! Right now the report is just a quick per-user breakdown,
        but we'll be adding more detail.</p>

      </div>
      <div class="col-md-4">
        <h3>Setting up Asana</h3>
        <p>All you have to do is add numeric tags to your existing tasks in
        Asana. You can still add other tags too; this tool will ignore any tag
        that isn't just a plain number.</p>
      </div>
      <div class="col-md-4">
        <h3>View Report</h3>
        <p>To tally the points, just enter your API key above and select your
        project from the list. By default you'll be shown the totals for the
        current week, but you can select any date range.</p>
      </div>
    </div>
  </div>
</div>

app/views/workspaces/form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <% if !@projects.empty? %>
      <% current_workspace = "" %>
      <% current_team      = "" %>
      <% @projects.each do |project| %>
        <% new_workspace = project['workspace']['name'] %>
        <% new_team      = project['team']['name'] %>
        <% if new_workspace != current_workspace %>
          <h1><%= "#{new_workspace}" %></h1>
          <% current_workspace = new_workspace %>
        <% end %>
        <% if new_team != current_team %>
          <h3><%= "#{new_team}" %></h3>
          <% current_team = new_team %>
        <% end %>
        <p>
          <%= link_to project['name'], report_path(project: { id: project['id'], name: project['name']}) %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/workspaces/report.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <h1><%= @project_name %></h1>
    <%= link_to 'Back to Projects List', form_path %>

    <%= form_tag({controller: "workspaces", action: "report"}, method: "get") do %>
      <%= hidden_field_tag "project[id]", @project_id %>
      <%= hidden_field_tag "project[name]", @project_name %>
      <div class="row input">
        <div class="col-sm-offset-2 col-sm-4">
          <%= label_tag :start_date, "Start Date", class: "control-label" %>
          <%= date_field_tag "project[start_date]", @start_date, class: "form-control date" %>
        </div>
        <div class="col-sm-4">
          <%= label_tag :end_date, "End Date", class: "control-label" %>
          <%= date_field_tag "project[end_date]", @end_date, class: "form-control date" %>
        </div>
      </div>
      <%= submit_tag "Change Dates", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <h3><%= @start_date.to_s(:long) %> to <%= @end_date.to_s(:long) %></h3>
    <p>
      <% if @report %>
        <% @report.each do |key, value| %>
          <p>
            <% if key != "Unassigned" %>
              <h4><%= key %> completed <%= value.sum %> points</h4>
            <% else %>
              <h4><%= value.sum %> points were completed, but unassigned</h4>
            <% end %>
          </p>
        <% end %>
      <% else %>
        <p>No tasks with points for this date range.</p>
      <% end %>
    </p>
  </div>
</div>